modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="placebo"

version="9.3.5"

displayName="Placebo"

authors="Shadows_of_Fire"

description='''1 (one) library boi'''

[[mixins]]
config="placebo.mixins.json"

[[dependencies.placebo]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.placebo]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.8,)"
    ordering="NONE"
    side="BOTH"